#!/usr/bin/env bash
echo "
===============
|  Running detekt...
===============
"

./gradlew --no-daemon --stacktrace -PdisablePreDex detekt

detektStatus=$?

[ $detektStatus -ne 0 ] && exit 1

echo "Running ktlintFormat..."

./gradlew ktlintFormat

echo "
===================
|  Running ktlintCheck...
===================
"

./gradlew --no-daemon --stacktrace -PdisablePreDex ktlintCheck

checkStyleStatus=$?

[ $checkStyleStatus -ne 0 ] && exit 1
exit 0